export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';
export const ADD_PLAYER = 'ADD_PLAYER';
export const DELETE_PLAYER = 'DELETE_PLAYER';
export const UPDATE_PLAYER = 'UPDATE_PLAYER';
export const GET_PLAYERS = 'GET_PLAYERS';